### ISSUE TITLE
Version v0.a11s7 Todo

### ISSUE THREAD

**Issue by Toma400** [Toma400/Wastelands_of_Baedoor#2]
As v0.a11s7 is approaching, I think it's good to organise "todo list" in some bulk topic, on GitHub this time:

## Features
- [ ] Patchouli
- [ ] Config:
  - [ ] 1.17
  - [ ] 1.18
- [ ] Airship loot tables:
  - [ ] Rechecking classic airships loot table (nerf)
  - [ ] Rechecking bandit airship loot table (nerf)
  - [ ] Creating trader airship loot table (composition)
    - [ ] Compatibilities moved to v0.a11s7b? (if so, put it in a way only loot table needs change, not the structure)
- [ ] Creating Trader Airship structure:
  - [ ] NBT structure
  - [ ] Mobs being added
  - [ ] Adding chest blocks

## Detailing & bugfixing
- [ ] Resolving 1.18 weird issue with custom code
- [ ] Fixing wandering trader model
- [ ] Fixing Bountiful & Tetra naming issues
- [ ] Checking changelog to see if there's changes on specific branch that wasn't ported to others

**Comment by Toma400** [comment]
Closing this as no longer possible to achieve - if we ever come back to this version, then welp, just open it again.
