### ISSUE TITLE
Version v0.ca1 Todo

### ISSUE THREAD

**Issue by Toma400** [Toma400/Wastelands_of_Baedoor#4]
CA (coded alpha) is new version system for coded ports of WoB for Fabric & Forge APIs, done for 1.19.2 version.

- [ ] Setting up basic workspace & Patchouli guide
  - [ ] Fabric
  - [ ] Forge
- [ ] Porting:
  - [x] Renewabilities:
    - [x] Diamonds
    - [x] Nether Soul Essence features
    - [x] Glistering Ash features
  - [ ] Mechanics:
    - [ ] Avoider block (placeholder way to get red obsidian - nether mining or some deep nether conversion)
- [ ] Patchouli

**Comment by Toma400** [comment]
Closing this as outdated.
